apiVersion: v1
kind: Service
metadata:
  name: seatbooking-service
  labels:
    app: seatbooking-app
    name: seatbooking-service
spec:
  selector:
    app: seatbooking-app
    name: seatbooking-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  seatbooking-deployment
  labels:
    app:  seatbooking-app
    name: seatbooking-deployment
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: seatbooking-pod
  #replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: seatbooking-pod
      labels:
        app: seatbooking-app
        name: seatbooking-pod
    spec:
      containers:
      - name: seatbooking-container
        image: dhamodaran/seatbooking_api:latest
        resources:
          requests:
             cpu: 500m
        ports:
        - containerPort:  3000    
